imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            # Production log files are rotated on a daily basis under a 30-day cycle.
            # This way we can avoid having huge log files, considering logs stale after 30 days.
            type:      rotating_file
            level:     notice
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 30
        console:
            type:  console
            level: debug
