services:
    wide.webmailauthenticator:
        class: WideBundle\Authentication\WebmailAuthenticator
        arguments: ["%imap_server_host%", "%imap_server_port%", "@logger"]
    wide.authenticator:
        class: WideBundle\Authentication\Authenticator
        arguments: ["@wide.webmailauthenticator", "@router", "%webmail_domain%"]
