services:
    wide.webmailauthenticator:
        class: WideBundle\Authentication\WebmailAuthenticator
        arguments: ["%imap_server_host%", "%imap_server_port%", "@logger"]
    wide.authenticator:
        class: WideBundle\Authentication\Authenticator
        arguments: ["@wide.webmailauthenticator", "@router", "@wide.registrationmanager", "%webmail_domain%"]
    wide.registrationmanager:
        class: WideBundle\Registration\RegistrationManager
        arguments: ["@doctrine.orm.entity_manager", "@logger",]
    wide.teammanager:
        class: WideBundle\Teams\TeamManager
        arguments: ["@doctrine.orm.entity_manager", "@wide.directory.handler", "@logger", "%files_directory%"]
    wide.directory.handler:
        class: WideBundle\FileSystemHandler\DirectoryHandler
        arguments: ["@logger"]
    wide.file.handler:
        class: WideBundle\FileSystemHandler\FileHandler
