services:
    wide.webmailauthenticator:
        class: WideBundle\Authentication\WebmailAuthenticator
        arguments: ["@vbee.manager.setting", "@logger"]
    wide.authenticator:
        class: WideBundle\Authentication\Authenticator
        arguments: ["@wide.webmailauthenticator", "@router", "@wide.registrationmanager", "@vbee.manager.setting"]
    wide.registrationmanager:
        class: WideBundle\Registration\RegistrationManager
        arguments: ["@doctrine.orm.entity_manager", "@logger", "@vbee.manager.setting"]
    wide.teammanager:
        class: WideBundle\Teams\TeamManager
        arguments: ["@doctrine.orm.entity_manager", "@wide.directory.handler", "@logger", "@vbee.manager.setting"]
    wide.directory.handler:
        class: WideBundle\FileSystemHandler\DirectoryHandler
        arguments: ["@logger", "@vbee.manager.setting"]
    wide.file.handler:
        class: WideBundle\FileSystemHandler\FileHandler
        arguments: ["@logger", "@vbee.manager.setting"]
    wide.utility.handler:
        class: WideBundle\Utility\UtilityHandler
        arguments: ["@wide.file.handler", "@wide.directory.handler", "%resource_map%"]
    wide.setting.handler:
        class: WideBundle\Setting\SettingHandler
        arguments: ["@vbee.manager.setting"]
    wide.search.manager:
        class: WideBundle\Search\SearchManager
        arguments: ["@doctrine.orm.entity_manager"]
    wide.exception_listener:
        class: WideBundle\EventListener\ExceptionListener
        arguments: ["@security.token_storage", "@router", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    wide.auth_listener:
        class: WideBundle\EventListener\AuthListener
        arguments: ["@security.token_storage", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 2 }
    wide.team_operation_listener:
        class: WideBundle\EventListener\TeamOperationListener
        arguments: ["@vbee.manager.setting", "@security.token_storage", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 1 }
    wide.team_resource_listener:
        class: WideBundle\EventListener\TeamResourceListener
        arguments: ["@security.token_storage", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }
    wide.editable_resource_listener:
        class: WideBundle\EventListener\EditableResourceListener
        arguments: ["@vbee.manager.setting", "@security.token_storage", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1 }
